# Generated by Django 4.0.1 on 2022-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_items_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='Latest new tecnology'),
        ),
    ]
