# Generated by Django 4.0.1 on 2022-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
